// src/utils/pdfGenerator.ts
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export const generateForecastPDF = async () => {
  const pdf = new jsPDF("p", "pt", "a4");
  const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));
  await delay(50); // Allow charts to fully render

  // ======= Cover Page =======
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(30);
  pdf.setTextColor(40);
  pdf.text("ProvansIQ Forecast Report", pdf.internal.pageSize.getWidth() / 2, 290, { align: "center" });

  pdf.setFontSize(14);
  pdf.setTextColor(60);
  pdf.text("Insights into Machine Health and Anomalies", pdf.internal.pageSize.getWidth() / 2, 340, { align: "center" });

  pdf.setFontSize(12);
  pdf.setTextColor(80);
  pdf.text(`This report includes forecasted trends and anomaly detections across temperature,`, pdf.internal.pageSize.getWidth() / 2, 400 ,  { align: "center" });
  pdf.text(`vibration, and pressure sensor metrics. It includes actual vs forecast comparisons,`, pdf.internal.pageSize.getWidth() / 2,420, { align: "center" });
  pdf.text( `anomaly heatmaps, and cross-metric analyses to assist in early issue detection.`, pdf.internal.pageSize.getWidth() / 2,440, { align: "center" });
  pdf.text(`The report is generated by ProvansIQ AI Engine.`, pdf.internal.pageSize.getWidth() / 2,720, { align: "center" });


  pdf.setFontSize(12);
  pdf.setTextColor(50);
  pdf.text("Generated on: " + new Date().toLocaleString(), pdf.internal.pageSize.getWidth() / 2, 740, { align: "center" });


  // Footer separator
  pdf.setFontSize(16);
  pdf.setTextColor(100);
  pdf.text("— Forecast Report —",pdf.internal.pageSize.getWidth() / 2, 700,{align: "center"});

  // ======= Charts Section =======
  const chartIds = [
    "chart-temperature",
    "chart-vibration",
    "chart-pressure",
    "chart-comparative",
    "chart-heatmap",
  ];

  for (let i = 0; i < chartIds.length; i++) {
    const chart = document.getElementById(chartIds[i]);
    if (chart) {
      try {
        await delay(50); // small delay
        const canvas = await html2canvas(chart);
        const imgData = canvas.toDataURL("image/png");

        pdf.addPage(); // always add page (we already used page 1 for cover)
        pdf.setFontSize(18);
        pdf.setTextColor(40);
        pdf.text(chartIds[i].replace("chart-", "").toUpperCase(), 40, 40);
        pdf.addImage(imgData, "PNG", 40, 60, 520, 390);

        pdf.setFontSize(12);
        pdf.setTextColor(80);
        pdf.text(getInsight(chartIds[i]), 40, 470, { maxWidth: 520 });
      } catch (error) {
        console.error(`Failed to capture chart: ${chartIds[i]}`, error);
      }
    } else {
      console.warn(`Chart not found: ${chartIds[i]}`);
    }
  }

  pdf.save("forecast_report.pdf");
};

const getInsight = (id: string) => {
  switch (id) {
    case "chart-temperature":
      return "Temperature trends help detect overheating or cooling issues. Sudden spikes or drops can signal maintenance needs.";
    case "chart-vibration":
      return "Abnormal vibration patterns may indicate mechanical imbalance, wear and tear, or misalignment.";
    case "chart-pressure":
      return "Pressure anomalies may result from blockages or leaks. Monitor deviations closely.";
    case "chart-comparative":
      return "Comparative analysis gives cross-metric insights. Correlation between temperature, vibration, and pressure can highlight root causes.";
    case "chart-heatmap":
      return "Heatmap highlights anomalies. Red intensity shows frequency and severity. Frequent anomalies at certain hours should trigger inspection.";
    default:
      return "";
  }
};

export default generateForecastPDF;
